### PR TITLE
fixing version of nerves_system_rpi4 to v1.13.0

### PR DESCRIPTION
**Pull request by takasehideki**
Due to issue about "wlan0" on 64-bit version of Raspbian OS (Linux kernel), we decided to fix the version of nerves_system_rpi4 to 1.13.0.

### CODE REVIEW

**Comment by takasehideki** [comment]
@pojiro please merge this if you want. Cancellation is acceptable if you have already adopted on your local environment.

**Comment by pojiro** [comment]
This commit seems no problem. I can rebase my fork branch after merging.
What can I do for merging this commit to main branch?

**Comment by takasehideki** [comment]
@pojiro You can merge this PR just by clicking "Merge pull request" button (appeared on this page with green color).
"Close pull request" without merging is another good choice, which cancels this PR, because you have already adopted this improvement on your local branch.

**Review by pojiro — APPROVED** [review]

**Comment by pojiro** [comment]
@takasehideki "Merge pull request" button doesn't show for me. Though I approved this commit as reviewer.

**Comment by pojiro** [comment]
@takasehideki  after approved and reloaded this page, the button shows. I could merged.

**Comment by takasehideki** [comment]
@pojiro so sorry,,, I should have changed the base permissions for this organization's members to "Write" from "read" :D

**Comment by takasehideki** [comment]
and you are now invited as the "admin" in this repository!

**Pull request merged**
