### PR TITLE
add feature, led on when vintage_net_wizard is running

### PR DESCRIPTION
**Pull request by pojiro**
@takasehideki Would you please review the feature you suggested?

### CODE REVIEW

**Comment by takasehideki** [comment]
@pojiro Works well on my environment. LATM!

I have a proposal for you. Would you like to turn off the LED at the proper timing?
The simple way is to turn LED on, wait a moment (e.g., `Process.sleep(10000)`), and then turn it off. I think this is enough to achieve. 

The way that seems to be good is to use "Stop callback". But it's a bit complicated and may not be worth the cost.
https://hexdocs.pm/vintage_net_wizard/readme.html#stop-callback

**Review by takasehideki — APPROVED** [review]

**Comment by pojiro** [comment]
Stop callback sounds nice. Ok, I'm gonna implement that.

**Comment by pojiro** [comment]
Now stop callback is implemented and tested. Would you please review this?

**Comment by takasehideki** [comment]
@pojiro I could not observe LED turned off, and log message "stop vintage net wizard" on RingLogger,,,

**Comment by pojiro** [comment]
We investigated why "complete" button doesn't display.

At least, vintage_net_wizard's WiFi daialog on iOS and Mac OS seems that transition is not as intended by the developers.

So I decided to disable captive portal feature as work around.

**Review by takasehideki — APPROVED** [review]
Completely works well! We did an amazing work!!

**Pull request merged**
